version: '3.3'

services:
   dsi2019walter:
     depends_on:
       - dbwalter  
     image: dsi2019walter:latest
     ports:
       - "8080:8080"
     restart: always
     environment:
       - SPRING_PROFILES_ACTIVE=prod
       - DSI2019_DB_HOST=jdbc:sqlserver://dbwalter:1433;databaseName=model
       - DSI2019_DB_USERNAME=SA
       - DSI2019_DB_PASSWORD=<YourStrong@Passw0rd>
   dbwalter:
     image: mcr.microsoft.com/mssql/server:2017-latest
     restart: always
     ports:
       - "1433:1433"
     environment:
       ACCEPT_EULA: Y
       SA_PASSWORD: <YourStrong@Passw0rd>
